### PR TITLE
Melhorar o tratamento de erros do servidor: definir "Internal Server Error" como mensagem para erros 500 e fornecer detalhes do erro na respost.

### LINKED ISSUE #14: Melhorar erros retornados pelo servidor
Nos casos em que um erro 500 é lançado, a propriedade `error.details` volta vazia já que o 
JavaScript não faz o parse do Error para string. Provavelmente seria interessante usar o `error.name` para indicar o nome do erro nos details.

### PR DESCRIPTION
**Pull request by carvalhoedsonn**
Resolves #14

### CODE REVIEW

**Comment by Gvinfinity** [comment]
Considerar possibilidade de implementação do protótipo `toJSON` para retornar segundo o padrão dos outros erros utilizando `JSON.stringify()`.

Confira: [Exemplo](https://stackoverflow.com/a/18391400/15635531)

**Comment by weltonfelix** [comment]
Conferir https://github.com/ifpeopensource/merenda-server/issues/14#issuecomment-1437840219.

**Comment by carvalhoedsonn** [comment]
> Conferir [#14 (comment)](https://github.com/ifpeopensource/merenda-server/issues/14#issuecomment-1437840219).

Resolved by [0e7a314](https://github.com/ifpeopensource/merenda-server/pull/15/commits/0e7a31402031322b4b798508e59aa9cff7ef1117)

**Comment by carvalhoedsonn** [comment]
> Conferir [#14 (comment)](https://github.com/ifpeopensource/merenda-server/issues/14#issuecomment-1437840219).

Resolved by [29f6dd4](https://github.com/ifpeopensource/merenda-server/pull/15/commits/29f6dd42c2951a6b53bfc11bb5491c1751accc25)

**Review by Gvinfinity — APPROVED** [review]

**Review by weltonfelix — APPROVED** [review]
LGTM!! 🚀

**Pull request merged**
